# file: postgresql/tasks/configure.yml

- name: Crowdsig Database | Copy all SQL scripts to remote
  synchronize:
    src: "files/"
    dest: " {{crowdsig_ddl_dir }} "

- name: Crowdsig Database | Execute DDL via psql
  command: "psql -U crowdsig -d postgres -f {{ crowdsig_ddl_dir }}/ddl.sql"

- name: Crowdsig Database | Execute DML via psql
  command: "psql -U crowdsig -d crowdsig -f {{ crowdsig_ddl_dir }}/dml.sql"

- name: Crowdsig Database | Execute City DML via psql
  command: "psql -U crowdsig -d crowdsig -f {{ crowdsig_ddl_dir }}/cities_dml.sql"

- name: Crowdsig Database | Execute Local Node DML via psql
  command: "psql -U crowdsig -d crowdsig -f {{ crowdsig_ddl_dir }}/local_keywords_dml.sql"
